//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTSellGold.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VNTSellGold.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string CapError {
            get {
                return ResourceManager.GetString("CapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string CapSave {
            get {
                return ResourceManager.GetString("CapSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        public static string CapWar {
            get {
                return ResourceManager.GetString("CapWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string ICol3Max {
            get {
                return ResourceManager.GetString("ICol3Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sao lưu xong..
        /// </summary>
        public static string MesBackup {
            get {
                return ResourceManager.GetString("MesBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi. Không thể sao lưu..
        /// </summary>
        public static string MesBackupError {
            get {
                return ResourceManager.GetString("MesBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có muốn xóa không ?.
        /// </summary>
        public static string MesDelete {
            get {
                return ResourceManager.GetString("MesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được rỗng..
        /// </summary>
        public static string MesEmpty {
            get {
                return ResourceManager.GetString("MesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được rỗng. Có muốn làm tiếp không ?.
        /// </summary>
        public static string MesEmptyYN {
            get {
                return ResourceManager.GetString("MesEmptyYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không thể cập nhật. Có thể thông tin đang được dùng..
        /// </summary>
        public static string MesErrorUpdate {
            get {
                return ResourceManager.GetString("MesErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy. Muốn tìm lại không ?.
        /// </summary>
        public static string MesFoundAgaint {
            get {
                return ResourceManager.GetString("MesFoundAgaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày phải nhỏ hơn đến ngày..
        /// </summary>
        public static string MesFromToDate {
            get {
                return ResourceManager.GetString("MesFromToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy thiết lập lại mã số lớn nhất..
        /// </summary>
        public static string MesICol3Full {
            get {
                return ResourceManager.GetString("MesICol3Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tháng không hợp lệ.
        /// </summary>
        public static string MesInvalidDate {
            get {
                return ResourceManager.GetString("MesInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy..
        /// </summary>
        public static string MesNotFound {
            get {
                return ResourceManager.GetString("MesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có chữ số nào được nhập. Số &quot;0&quot; được thay thế ?.
        /// </summary>
        public static string MesNumEmpty {
            get {
                return ResourceManager.GetString("MesNumEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu xong.
        /// </summary>
        public static string MesSaveOk {
            get {
                return ResourceManager.GetString("MesSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
    }
}
